--- #YAML:1.0
name:                XML-TMX
version:             0.16
abstract:            TMX tools
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    Exporter:                      0
    Test::Pod:                     1
    Test::Pod::Coverage:           0.08
    XML::DT:                       0.27
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - Projecto Natura
